# This workflow will run tests using node.
name: Run NodeJS Tests

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Run on every push.
  push:

  # Run on every pull request.
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [ 10, 12, 14, 16, 18, 20 ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      # Clean install of all dependencies.
      - run: npm ci

      # Run the tests
      - run: npm test

      # Generate coverage.
      # Note: Commented out until vsiakka can configure this.
      #- run: npm run coverage
